### PR TITLE
v1.4

### PR DESCRIPTION
**Pull request by aledj2**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaamp_workflow/5)

### CODE REVIEW

**Comment by Graeme-Smith** [comment]
___
*[mokaamp_description.txt, line 148 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaamp_workflow/5#-MJlSKC70uPEU_qKIG7l:-MJlSKC70uPEU_qKIG7m:b-1f1gey) ([raw file](https://github.com/moka-guys/dnanexus_mokaamp_workflow/blob/d781a6bad6b0f762bb7a445c64cbb57f6e9a6fb0/mokaamp_description.txt#L148)):*
> ```vimhelp
>                 stage-FPzGjp80jy1V3Jvb5z6xfpfZ: Common:
>                     [stage-FPzGjp80jy1V3Jvb5z6xfpfZ.min_BQ (string,
>                   default="15")]
> ```

`min_BQ` has been changed from 13 to 15? The previous version also included a parameter `min_avg_qual` = 15 which is not included in this version?

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaamp_workflow/5)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @aledj2 and @Graeme-Smith)

**Review by aledj2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaamp_workflow/5)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

___
*[mokaamp_description.txt, line 148 at r1](https://reviewable.io/reviews/moka-guys/dnanexus_mokaamp_workflow/5#-MJlSKC70uPEU_qKIG7l:-MJlUam67r-PoWSRfIqj:b-l5f4sy) ([raw file](https://github.com/moka-guys/dnanexus_mokaamp_workflow/blob/d781a6bad6b0f762bb7a445c64cbb57f6e9a6fb0/mokaamp_description.txt#L148)):*
<details><summary><i>Previously, Graeme-Smith (Graeme) wrote…</i></summary><blockquote>

`min_BQ` has been changed from 13 to 15? The previous version also included a parameter `min_avg_qual` = 15 which is not included in this version?
</blockquote></details>

yes, these changes have been validated within the app itself. - basically there were options to state a different base quality for mpileup and varscan - the app now has one parameter which is supplied to both tools

**Review by Graeme-Smith — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaamp_workflow/5)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @Graeme-Smith)

**Review by Graeme-Smith — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/dnanexus_mokaamp_workflow/5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
